-- Reusable functions for getting ANALYSIS and COMPONENT data

CREATE 
  OR REPLACE FUNCTION analysis_data(analysis_version INTEGER) RETURNS TABLE (
  STATUS TEXT, ACTION TEXT, NAME CHARACTER VARYING(20), VERSION INTEGER, GROUP_NAME CHARACTER VARYING(20), 
  ACTIVE CHARACTER VARYING(1), REPORTED_NAME CHARACTER VARYING(30), COMMON_NAME CHARACTER VARYING(20), 
  ANALYSIS_TYPE CHARACTER VARYING(20), DESCRIPTION CHARACTER VARYING(254), ALIAS_NAME CHARACTER VARYING(40),
  LAB CHARACTER VARYING(20), INST_GROUP CHARACTER VARYING(20), INSTRUMENT CHARACTER VARYING(20), 
  TEST_LOCATION CHARACTER VARYING(20), EXPECTED_DATE INTEGER, COST_UNITS DOUBLE PRECISION, 
  REQD_VOLUME DOUBLE PRECISION, DESTRUCTIVE CHARACTER VARYING(1), PARAMETER_NAME CHARACTER VARYING(20),
  PARAMETER_TAG CHARACTER VARYING(50), DISPLAY_MESSAGE CHARACTER VARYING(60), KEY_CONTACT CHARACTER VARYING(20), 
  CHANGED_ON TIMESTAMP WITHOUT TIME ZONE, CHANGED_BY TEXT, REMOVED TEXT, EXT_LINK CHARACTER VARYING(254),
  TEST_TEMPLATE TEXT, BATCH_LINK CHARACTER VARYING(20), AUTO_AUTHORIZE CHARACTER VARYING(1), 
  AUTO_REJECT CHARACTER VARYING(1), CALC_ON_SAVE CHARACTER VARYING(1), STORE_INCMP_OPTS CHARACTER VARYING(1), 
  ALIQUOT_GROUP TEXT, SPLIT_REPLICATES CHARACTER VARYING(1), CROSS_SAMPLE CHARACTER VARYING(1), 
  SAMPLE_TYPE CHARACTER VARYING(20), CONTAINER_TYPE CHARACTER VARYING(20), STORAGE_CONDITION CHARACTER VARYING(20), 
  APPROVAL_ROLE CHARACTER VARYING(20), QUICK_CODE CHARACTER VARYING(5), VOLUME_UNITS CHARACTER VARYING(20), 
  HIDE_ON_ORDER_FORM CHARACTER VARYING(1), TEST_SEQUENCE_NO INTEGER, DOUBLE_ENTRY CHARACTER VARYING(1), 
  MILL_FORMAT_CALC TEXT, ALLOW_MILL_ADHOCS TEXT, TRANSFER_USES_INST CHARACTER VARYING(1), ATTRIBUTE_1 TEXT, 
  ATTRIBUTE_10 TEXT, ATTRIBUTE_11 TEXT, ATTRIBUTE_12 TEXT, ATTRIBUTE_13 TEXT, ATTRIBUTE_14 TEXT, ATTRIBUTE_15 TEXT, 
  ATTRIBUTE_16 TEXT, ATTRIBUTE_17 TEXT, ATTRIBUTE_18 TEXT, ATTRIBUTE_19 TEXT, ATTRIBUTE_2 TEXT, ATTRIBUTE_20 TEXT, 
  ATTRIBUTE_3 TEXT, ATTRIBUTE_4 TEXT, ATTRIBUTE_5 TEXT, ATTRIBUTE_6 TEXT, ATTRIBUTE_7 TEXT, ATTRIBUTE_8 TEXT, 
  ATTRIBUTE_9 TEXT, T_PH_PARENT_ANALYSIS TEXT, EXTERNAL_ID TEXT, T_NUM_STAGES TEXT, T_AUTO_ADD_STAGE TEXT, 
  T_NEXT_STAGE_ANALYSIS TEXT, T_NEXT_STAGE_TEST_LIST TEXT, T_DISS_TP_DISPLAY TEXT, T_NEXT_STAGE_TEST_LIST_S3 TEXT, 
  T_COA_METHOD_REFERENCE TEXT, T_METHOD_REFERENCE TEXT, T_TESTING_INTERVAL TEXT, EN_REPORTED_NAME CHARACTER VARYING(30), 
  ES_DESCRIPTION CHARACTER VARYING(254), ES_REPORTED_NAME CHARACTER VARYING(30), FR_DESCRIPTION CHARACTER VARYING(254),
  FR_REPORTED_NAME CHARACTER VARYING(30), IT_DESCRIPTION CHARACTER VARYING(254), IT_REPORTED_NAME CHARACTER VARYING(30),
  PT_DESCRIPTION CHARACTER VARYING(254), PT_REPORTED_NAME CHARACTER VARYING(30), T_BCI_DILUTION TEXT, 
  T_BCI_TESTDETAILS TEXT, T_DIL_COMMENT TEXT, T_DIL_DILUENT CHARACTER VARYING(20), T_DIL_PROG_DILUENT_TOLERANCE INTEGER, 
  T_DIL_PROG_DILUENT_VERIFIED CHARACTER VARYING(1), T_DIL_PROG_IS_PUBLIC CHARACTER VARYING(1),
  T_DIL_PROG_MODE CHARACTER VARYING(10), T_DIL_PROG_SMP_MASS_THEORETICAL DOUBLE PRECISION,
  T_DIL_PROG_SMP_MASS_TOLERANCE DOUBLE PRECISION,T_DIL_PROG_SUPLEMENT_FIRST CHARACTER VARYING(1),
  T_DIL_PROG_SUPLEMENT_MODE CHARACTER VARYING(10), T_DIL_PROG_TARGET TEXT, T_DIL_PROG_TYPE CHARACTER VARYING(20), 
  T_DIL_SMPL_W_MAX TEXT, T_DIL_SMPL_W_MIN TEXT, T_INCUBATION_TIME CHARACTER VARYING(30),
  T_METHOD_ISO_REF CHARACTER VARYING(30), T_TEMP_INCUB_ISO_BAM CHARACTER VARYING(30), T_ENV_MAP TEXT, T_LAB_TYPE TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT
        'Ready' AS status,
        CASE WHEN A.VERSION = 1 THEN 'Insert'
            ELSE 'Update & Version'
        END AS action,
        A.NAME,
        CASE WHEN A.VERSION > 1 THEN A.VERSION - 1
            ELSE A.VERSION
        END AS version,
    A.GROUP_NAME, A.ACTIVE, A.REPORTED_NAME, A.COMMON_NAME, A.ANALYSIS_TYPE, A.DESCRIPTION, A.ALIAS_NAME, 
    A.LAB, A.INST_GROUP, I.NAME AS INSTRUMENT, A.TEST_LOCATION, A.EXPECTED_DATE, A.COST_UNITS, A.REQD_VOLUME, 
    A.DESTRUCTIVE, A.PARAMETER_NAME, A.PARAMETER_TAG, A.DISPLAY_MESSAGE, A.KEY_CONTACT, 
    NULL::TIMESTAMP WITHOUT TIME ZONE AS CHANGED_ON, NULL AS CHANGED_BY, 'F' AS REMOVED, A.EXT_LINK, 
    NULL AS TEST_TEMPLATE, A.BATCH_LINK, A.AUTO_AUTHORIZE, A.AUTO_REJECT, A.CALC_ON_SAVE, A.STORE_INCMP_OPTS, 
    NULL AS ALIQUOT_GROUP, A.SPLIT_REPLICATES, A.CROSS_SAMPLE, A.SAMPLE_TYPE, A.CONTAINER_TYPE, A.STORAGE_CONDITION, 
    A.APPROVAL_ROLE, A.QUICK_CODE, A.VOLUME_UNITS, A.HIDE_ON_ORDER_FORM, A.TEST_SEQUENCE_NO, A.DOUBLE_ENTRY, 
    NULL AS MILL_FORMAT_CALC, 'F' AS ALLOW_MILL_ADHOCS, A.TRANSFER_USES_INST, NULL AS ATTRIBUTE_1, NULL AS ATTRIBUTE_10, 
    NULL AS ATTRIBUTE_11, NULL AS ATTRIBUTE_12, NULL AS ATTRIBUTE_13, NULL AS ATTRIBUTE_14, NULL AS ATTRIBUTE_15, 
    NULL AS ATTRIBUTE_16, NULL AS ATTRIBUTE_17, NULL AS ATTRIBUTE_18, NULL AS ATTRIBUTE_19, NULL AS ATTRIBUTE_2, 
    NULL AS ATTRIBUTE_20, NULL AS ATTRIBUTE_3, NULL AS ATTRIBUTE_4, NULL AS ATTRIBUTE_5, NULL AS ATTRIBUTE_6, 
    NULL AS ATTRIBUTE_7, NULL AS ATTRIBUTE_8, NULL AS ATTRIBUTE_9, NULL AS T_PH_PARENT_ANALYSIS, NULL AS EXTERNAL_ID, 
    NULL AS T_NUM_STAGES, NULL AS T_AUTO_ADD_STAGE, NULL AS T_NEXT_STAGE_ANALYSIS, NULL AS T_NEXT_STAGE_TEST_LIST, 
    NULL AS T_DISS_TP_DISPLAY, NULL AS T_NEXT_STAGE_TEST_LIST_S3, NULL AS T_COA_METHOD_REFERENCE, 
    NULL AS T_METHOD_REFERENCE, NULL AS T_TESTING_INTERVAL, A.EN_REPORTED_NAME, A.ES_DESCRIPTION, A.ES_REPORTED_NAME, 
    A.FR_DESCRIPTION, A.FR_REPORTED_NAME, A.IT_DESCRIPTION, A.IT_REPORTED_NAME, A.PT_DESCRIPTION, A.PT_REPORTED_NAME, 
    NULL AS T_BCI_DILUTION, NULL AS T_BCI_TESTDETAILS, NULL AS T_DIL_COMMENT, A.T_DIL_DILUENT, 
    A.T_DIL_PROG_DILUENT_TOLERANCE, A.T_DIL_PROG_DILUENT_VERIFIED, A.T_DIL_PROG_IS_PUBLIC, A.T_DIL_PROG_MODE, 
    A.T_DIL_PROG_SMP_MASS_THEORETICAL, A.T_DIL_PROG_SMP_MASS_TOLERANCE, A.T_DIL_PROG_SUPLEMENT_FIRST, 
    A.T_DIL_PROG_SUPLEMENT_MODE, NULL AS T_DIL_PROG_TARGET, A.T_DIL_PROG_TYPE, NULL AS T_DIL_SMPL_W_MAX, 
    NULL AS T_DIL_SMPL_W_MIN, A.T_INCUBATION_TIME, A.T_METHOD_ISO_REF, A.T_TEMP_INCUB_ISO_BAM, NULL AS T_ENV_MAP, 
    NULL AS T_LAB_TYPE
    FROM ANALYSIS A
    LEFT JOIN TEST T ON A.NAME = T.ANALYSIS AND A.VERSION = T.VERSION
    LEFT JOIN INSTRUMENTS I ON A.INSTRUMENT = I.NAME AND I.REMOVED = 'F'
    WHERE (T.TEST_NUMBER IS NULL OR A.REMOVED = 'F')
      AND A.VERSION = analysis_version
    ORDER BY A.NAME ASC;
END;
$$ LANGUAGE PLPGSQL;

CREATE 
  OR REPLACE FUNCTION components_data(analysis_version INTEGER)
RETURNS TABLE (
    status TEXT, action TEXT, analysis CHARACTER VARYING(20),
    name CHARACTER VARYING(40), version INTEGER, order_number INTEGER,  result_type CHARACTER VARYING(1),
    units CHARACTER VARYING(20), minimum CHARACTER VARYING(20), maximum CHARACTER VARYING(20),
    allow_out CHARACTER VARYING(1), places INTEGER, num_replicates INTEGER, uses_instrument CHARACTER VARYING(1),
    uses_codes CHARACTER VARYING(1), auto_calc CHARACTER VARYING(1), list_key CHARACTER VARYING(20),
    allow_cancel CHARACTER VARYING(1), cas_number CHARACTER VARYING(20), alias_name CHARACTER VARYING(40),
    reportable CHARACTER VARYING(1), optional CHARACTER VARYING(1), round CHARACTER VARYING(20),
    clamp_low CHARACTER VARYING(20), clamp_high CHARACTER VARYING(20), std_reag_template CHARACTER VARYING(20),
    has_attributes CHARACTER VARYING(1), format_calculation CHARACTER VARYING(20), displayed CHARACTER VARYING(1),
    version_files CHARACTER VARYING(1), browse_subroutine CHARACTER VARYING(50), step CHARACTER VARYING(20),
    nwa_name TEXT,  t_hide_calc_on_worksheet TEXT, t_hide_on_worksheet TEXT,  t_ph_aql_reps TEXT, 
    t_ph_aql_type TEXT, external_id TEXT, sap_replicates TEXT, t_supplied_rslt TEXT, t_supplied_rslt_type TEXT, 
    places_2 INTEGER, reported_result CHARACTER VARYING(1), conversion_type CHARACTER VARYING(20),
    from_category CHARACTER VARYING(20), to_category CHARACTER VARYING(20), from_units CHARACTER VARYING(20),
    to_units CHARACTER VARYING(20), conversion_factor DOUBLE PRECISION, t_stock TEXT, 
    t_inst_group TEXT, t_instrument TEXT, t_xml_tag CHARACTER VARYING(40)
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT
        'Ready' AS status, 
        CASE 
            WHEN c2.name IS NOT NULL THEN 'Update'
            WHEN c2.name IS NULL THEN 'Insert'
        END AS action,  
        C.ANALYSIS, C.NAME, C.VERSION, C.ORDER_NUMBER, 
        C.RESULT_TYPE, C.UNITS, C.MINIMUM, C.MAXIMUM, C.ALLOW_OUT, C.PLACES, C.NUM_REPLICATES, 
        C.USES_INSTRUMENT, C.USES_CODES, C.AUTO_CALC, C.LIST_KEY, C.ALLOW_CANCEL, C.CAS_NUMBER, 
        C.ALIAS_NAME, C.REPORTABLE, C.OPTIONAL, C.ROUND, C.CLAMP_LOW, C.CLAMP_HIGH, 
        CASE 
            WHEN C.STD_REAG_TEMPLATE = 'BROTH1' THEN 'BROTH_DILUMAT'::CHARACTER VARYING(20)
            ELSE C.STD_REAG_TEMPLATE 
        END AS STD_REAG_TEMPLATE, 
        C.HAS_ATTRIBUTES, C.FORMAT_CALCULATION, C.DISPLAYED, C.VERSION_FILES, C.BROWSE_SUBROUTINE, 
        C.STEP, NULL AS NWA_NAME, 'F' AS T_HIDE_CALC_ON_WORKSHEET, NULL AS T_HIDE_ON_WORKSHEET, 
        NULL AS T_PH_AQL_REPS, NULL AS T_PH_AQL_TYPE, NULL AS EXTERNAL_ID, NULL AS SAP_REPLICATES, 
        NULL AS T_SUPPLIED_RSLT, NULL AS T_SUPPLIED_RSLT_TYPE, C.PLACES_2, C.REPORTED_RESULT, 
        C.CONVERSION_TYPE, C.FROM_CATEGORY, C.TO_CATEGORY, C.FROM_UNITS, C.TO_UNITS, 
        C.CONVERSION_FACTOR, NULL AS T_STOCK, NULL AS T_INST_GROUP, NULL AS T_INSTRUMENT, 
        C.T_XML_TAG 
    FROM COMPONENT C 
    INNER JOIN ANALYSIS A ON A.NAME = C.ANALYSIS AND A.VERSION = C.VERSION
    LEFT JOIN TEST T ON A.NAME = T.ANALYSIS AND A.VERSION = T.VERSION
    LEFT JOIN COMPONENT C2 ON C.NAME = C2.NAME AND C.ANALYSIS = C2.ANALYSIS AND (C.VERSION - 1 = C2.VERSION)
    WHERE (T.TEST_NUMBER IS NULL OR A.REMOVED = 'F')
      AND A.VERSION = analysis_version
    UNION
    SELECT DISTINCT
        'Ready' AS status, 'Remove' AS action,  
        C.ANALYSIS, C.NAME, C.VERSION + 1, C.ORDER_NUMBER, 
        C.RESULT_TYPE, C.UNITS, C.MINIMUM, C.MAXIMUM, C.ALLOW_OUT, C.PLACES, C.NUM_REPLICATES, 
        C.USES_INSTRUMENT, C.USES_CODES, C.AUTO_CALC, C.LIST_KEY, C.ALLOW_CANCEL, C.CAS_NUMBER, 
        C.ALIAS_NAME, C.REPORTABLE, C.OPTIONAL, C.ROUND, C.CLAMP_LOW, C.CLAMP_HIGH, 
        CASE 
            WHEN C.STD_REAG_TEMPLATE = 'BROTH1' THEN 'BROTH_DILUMAT'::CHARACTER VARYING(20)
            ELSE C.STD_REAG_TEMPLATE 
        END AS STD_REAG_TEMPLATE, 
        C.HAS_ATTRIBUTES, C.FORMAT_CALCULATION, C.DISPLAYED, C.VERSION_FILES, C.BROWSE_SUBROUTINE, 
        C.STEP, NULL AS NWA_NAME, 'F' AS T_HIDE_CALC_ON_WORKSHEET, NULL AS T_HIDE_ON_WORKSHEET, 
        NULL AS T_PH_AQL_REPS, NULL AS T_PH_AQL_TYPE, NULL AS EXTERNAL_ID, NULL AS SAP_REPLICATES, 
        NULL AS T_SUPPLIED_RSLT, NULL AS T_SUPPLIED_RSLT_TYPE, C.PLACES_2, C.REPORTED_RESULT, 
        C.CONVERSION_TYPE, C.FROM_CATEGORY, C.TO_CATEGORY, C.FROM_UNITS, C.TO_UNITS, 
        C.CONVERSION_FACTOR, NULL AS T_STOCK, NULL AS T_INST_GROUP, NULL AS T_INSTRUMENT, 
        C.T_XML_TAG 
    FROM COMPONENT C 
    INNER JOIN ANALYSIS A ON A.NAME = C.ANALYSIS AND A.VERSION = C.VERSION
    LEFT JOIN TEST T ON A.NAME = T.ANALYSIS AND A.VERSION = T.VERSION
    LEFT JOIN COMPONENT C2 ON C.NAME = C2.NAME AND C.ANALYSIS = C2.ANALYSIS
    WHERE (T.TEST_NUMBER IS NULL OR A.REMOVED = 'F')
      AND A.VERSION = (analysis_version - 1)
      AND C2.NAME IS NULL
    ORDER BY 3, 4 ASC;
END;
$$ LANGUAGE plpgsql;
